import { useState, useEffect, useMemo } from "react";
import { Link } from "react-router-dom";
import { BASE_GAMES } from "../data/games.js";
import { BASE_CATEGORIES } from "../data/categories.js";
import { PLATFORMS } from "../data/platforms.js";
import { useAuth } from "../lib/auth.jsx";
import { supabaseEnabled } from "../lib/supabase.js";
import AuthModal from "../components/AuthModal.jsx";
import {
  fetchLiveGames, fetchLiveCategories,
  upsertGames, deleteGameById,
  upsertCategories, deleteCategoryByKey,
} from "../lib/db.js";

/* ===========================================================
   GAMEZY ADMIN
   - If Supabase is configured AND you're signed in as an admin,
     changes save to the database and go live for every visitor.
   - Otherwise, edits stay in your browser; use Export to update source.
   - Local password is a fallback when Supabase isn't set up.
   =========================================================== */
const ADMIN_PASSWORD = "gamezy2026";

const LS_GAMES = "gamezy_games_v1";
const LS_CATS  = "gamezy_categories_v1";
const SS_AUTH  = "gamezy_admin_auth";

function loadLocalGames() {
  try {
    const v = localStorage.getItem(LS_GAMES);
    if (v) { const p = JSON.parse(v); if (Array.isArray(p) && p.length) return p; }
  } catch (e) {}
  return JSON.parse(JSON.stringify(BASE_GAMES));
}
function loadLocalCats() {
  try {
    const v = localStorage.getItem(LS_CATS);
    if (v) { const p = JSON.parse(v); if (Array.isArray(p) && p.length) return p; }
  } catch (e) {}
  return JSON.parse(JSON.stringify(BASE_CATEGORIES));
}
function saveLocalGames(g) { localStorage.setItem(LS_GAMES, JSON.stringify(g)); }
function saveLocalCats(c)  { localStorage.setItem(LS_CATS,  JSON.stringify(c)); }

function slugify(s) {
  return String(s || "").toLowerCase().trim()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function exportGamesJs(games) {
  const body = games.map((g) => "  " + JSON.stringify(g)).join(",\n");
  return `/* GameZy games (generated by admin export). */
export const BASE_GAMES = [
${body}
];

let _runtime = BASE_GAMES;
try {
  if (typeof localStorage !== "undefined") {
    const v = localStorage.getItem("gamezy_games_v1");
    if (v) {
      const parsed = JSON.parse(v);
      if (Array.isArray(parsed) && parsed.length) _runtime = parsed;
    }
  }
} catch (e) {}
export const GAMES = _runtime;
export const gameBySlug = (s) => GAMES.find((g) => g.slug === s);
`;
}
function exportCatsJs(cats) {
  const body = cats.map((c) => "  " + JSON.stringify(c)).join(",\n");
  return `/* GameZy categories (generated by admin export). */
export const BASE_CATEGORIES = [
${body}
];

let _rt = BASE_CATEGORIES;
try {
  if (typeof localStorage !== "undefined") {
    const v = localStorage.getItem("gamezy_categories_v1");
    if (v) {
      const p = JSON.parse(v);
      if (Array.isArray(p) && p.length) _rt = p;
    }
  }
} catch (e) {}
export const CATEGORIES = _rt;
export const catName = (k) => (CATEGORIES.find((c) => c.key === k) || {}).name || k;
export const catShort = (k) => {
  const c = CATEGORIES.find((x) => x.key === k);
  return (c && c.short) || ({ action: "Action", shooter: "Shooter", rpg: "RPG", sports: "Sports", horror: "Horror", indie: "Indie" }[k]) || k;
};
`;
}
function downloadText(name, text) {
  const blob = new Blob([text], { type: "text/javascript;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = name;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/* =================== LOGIN GATE =================== */
function LoginGate({ onAuth, openSupabaseAuth }) {
  const [pw, setPw] = useState("");
  const [err, setErr] = useState("");
  const submit = (e) => {
    e.preventDefault();
    if (pw === ADMIN_PASSWORD) {
      sessionStorage.setItem(SS_AUTH, "1");
      onAuth();
    } else {
      setErr("Wrong password. Try again.");
      setPw("");
    }
  };
  return (
    <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", padding: 20 }}>
      <form onSubmit={submit} style={{ background: "rgba(28,22,40,.85)", border: "1px solid rgba(231,167,43,.3)", borderRadius: 14, padding: 28, maxWidth: 400, width: "100%" }}>
        <h1 className="gold-text" style={{ fontSize: 26, marginBottom: 6 }}>GameZy Admin</h1>
        <p className="muted" style={{ fontSize: 13, marginBottom: 18 }}>
          {supabaseEnabled ? (
            <>Use your GameZy account (must be flagged as admin) for live edits, or the local password for offline edits.</>
          ) : (
            <>Enter the admin password to continue.</>
          )}
        </p>
        {supabaseEnabled && (
          <>
            <button type="button" className="btn btn-purple" onClick={openSupabaseAuth} style={{ width: "100%", marginBottom: 10 }}>
              Sign in with my GameZy account
            </button>
            <div style={{ display: "flex", alignItems: "center", gap: 8, margin: "12px 0" }}>
              <div style={{ flex: 1, height: 1, background: "rgba(255,255,255,.08)" }} />
              <span className="muted" style={{ fontSize: 11, textTransform: "uppercase", letterSpacing: 1 }}>or local password</span>
              <div style={{ flex: 1, height: 1, background: "rgba(255,255,255,.08)" }} />
            </div>
          </>
        )}
        <input type="password" placeholder="Local admin password" value={pw} onChange={(e) => setPw(e.target.value)} autoFocus
          style={{ width: "100%", padding: "12px 14px", borderRadius: 10, border: "1px solid rgba(255,255,255,.15)", background: "rgba(0,0,0,.35)", color: "#fff", fontSize: 16 }} />
        {err && <div style={{ color: "#ff6b6b", marginTop: 10, fontSize: 13 }}>{err}</div>}
        <button className="btn btn-gold" type="submit" style={{ marginTop: 14, width: "100%" }}>Use local password</button>
        <div style={{ marginTop: 16, textAlign: "center" }}>
          <Link to="/" className="muted" style={{ fontSize: 13 }}>&larr; Back to site</Link>
        </div>
      </form>
    </div>
  );
}

function emptyGame() {
  const id = Date.now();
  return {
    id, slug: "new-game-" + id, title: "New Game",
    cat: "action", plat: ["pc"], year: new Date().getFullYear(),
    dev: "Studio", rating: 4.0, c: ["#5e2a8c", "#e7a72b"],
    tagline: "", summary: "", about: "",
    features: [], tags: [], reviews: [],
  };
}

function GameEditor({ game, cats, onSave, onCancel, onDelete }) {
  const [g, setG] = useState(() => JSON.parse(JSON.stringify(game)));
  const set = (k, v) => setG((x) => ({ ...x, [k]: v }));
  const setPlat = (key) => {
    const arr = g.plat.includes(key) ? g.plat.filter((p) => p !== key) : [...g.plat, key];
    set("plat", arr);
  };
  const save = () => {
    const clean = { ...g };
    clean.slug = slugify(g.slug || g.title);
    clean.rating = Math.max(0, Math.min(5, parseFloat(g.rating) || 0));
    clean.year = parseInt(g.year) || new Date().getFullYear();
    clean.features = (g.features || []).filter((x) => x && x.trim());
    clean.tags = (g.tags || []).filter((x) => x && x.trim());
    clean.plat = g.plat && g.plat.length ? g.plat : ["pc"];
    if (!clean.c || clean.c.length !== 2) clean.c = ["#5e2a8c", "#e7a72b"];
    onSave(clean);
  };

  const row = { display: "grid", gridTemplateColumns: "160px 1fr", gap: 12, alignItems: "center", marginBottom: 12 };
  const lab = { color: "#cbb8e4", fontSize: 13 };
  const inp = { width: "100%", padding: "10px 12px", borderRadius: 8, border: "1px solid rgba(255,255,255,.12)", background: "rgba(0,0,0,.3)", color: "#fff", fontSize: 14 };

  return (
    <div style={{ background: "rgba(20,15,30,.9)", border: "1px solid rgba(231,167,43,.25)", borderRadius: 14, padding: 22, marginTop: 16 }}>
      <h3 className="gold-text" style={{ fontSize: 20, marginBottom: 16 }}>{game.id ? "Edit game" : "New game"}</h3>
      <div style={row}><label style={lab}>Title</label><input style={inp} value={g.title} onChange={(e) => set("title", e.target.value)} /></div>
      <div style={row}><label style={lab}>Slug (URL)</label><input style={inp} value={g.slug} onChange={(e) => set("slug", e.target.value)} /></div>
      <div style={row}><label style={lab}>Category</label>
        <select style={inp} value={g.cat} onChange={(e) => set("cat", e.target.value)}>
          {cats.map((c) => <option key={c.key} value={c.key}>{c.name}</option>)}
        </select></div>
      <div style={row}><label style={lab}>Platforms</label>
        <div style={{ display: "flex", gap: 14, flexWrap: "wrap" }}>
          {PLATFORMS.map((p) => (
            <label key={p.key} style={{ display: "flex", alignItems: "center", gap: 6, color: "#cbb8e4", fontSize: 14 }}>
              <input type="checkbox" checked={g.plat.includes(p.key)} onChange={() => setPlat(p.key)} />{p.name}
            </label>
          ))}
        </div></div>
      <div style={row}><label style={lab}>Year</label><input style={inp} type="number" value={g.year} onChange={(e) => set("year", e.target.value)} /></div>
      <div style={row}><label style={lab}>Developer</label><input style={inp} value={g.dev} onChange={(e) => set("dev", e.target.value)} /></div>
      <div style={row}><label style={lab}>Rating (0-5)</label><input style={inp} type="number" step="0.1" min="0" max="5" value={g.rating} onChange={(e) => set("rating", e.target.value)} /></div>
      <div style={row}><label style={lab}>Image path</label><input style={inp} placeholder="/images/games/your-slug.jpg" value={g.image || ""} onChange={(e) => set("image", e.target.value)} /></div>
      <div style={row}><label style={lab}>Colour 1</label><input style={{ ...inp, height: 40, padding: 4 }} type="color" value={g.c[0]} onChange={(e) => set("c", [e.target.value, g.c[1]])} /></div>
      <div style={row}><label style={lab}>Colour 2</label><input style={{ ...inp, height: 40, padding: 4 }} type="color" value={g.c[1]} onChange={(e) => set("c", [g.c[0], e.target.value])} /></div>
      <div style={row}><label style={lab}>Tagline</label><input style={inp} value={g.tagline} onChange={(e) => set("tagline", e.target.value)} /></div>
      <div style={row}><label style={lab}>Summary</label><textarea style={{ ...inp, minHeight: 70 }} value={g.summary} onChange={(e) => set("summary", e.target.value)} /></div>
      <div style={row}><label style={lab}>About (long)</label><textarea style={{ ...inp, minHeight: 110 }} value={g.about} onChange={(e) => set("about", e.target.value)} /></div>
      <div style={row}><label style={lab}>Features (one per line)</label><textarea style={{ ...inp, minHeight: 90 }} value={(g.features || []).join("\n")} onChange={(e) => set("features", e.target.value.split("\n"))} /></div>
      <div style={row}><label style={lab}>Tags (comma separated)</label><input style={inp} value={(g.tags || []).join(", ")} onChange={(e) => set("tags", e.target.value.split(",").map((x) => x.trim()))} /></div>

      <div style={{ display: "flex", gap: 10, marginTop: 18, flexWrap: "wrap" }}>
        <button className="btn btn-gold" onClick={save}>Save</button>
        <button className="btn btn-purple" onClick={onCancel}>Cancel</button>
        {game.id && onDelete && (
          <button className="btn" style={{ background: "#7a1c1c", color: "#fff", marginLeft: "auto" }}
            onClick={() => { if (confirm("Delete \"" + g.title + "\"?")) onDelete(g.id); }}>Delete game</button>
        )}
      </div>
    </div>
  );
}

function CategoryEditor({ cats, onSet, games }) {
  const [editing, setEditing] = useState(null);
  const isNew = editing && !cats.find((c) => c.key === editing.__origKey);
  const startNew = () => setEditing({ key: "", name: "", blurb: "", c: ["#5e2a8c", "#e7a72b"] });
  const save = () => {
    const key = slugify(editing.key || editing.name);
    const e = { ...editing, key }; delete e.__origKey;
    let next;
    if (isNew) next = [...cats, e];
    else next = cats.map((c) => (c.key === editing.__origKey ? e : c));
    onSet(next); setEditing(null);
  };
  const remove = (key) => {
    const inUse = games.filter((g) => g.cat === key).length;
    if (inUse > 0) { alert(inUse + " game(s) still use this category. Reassign them first."); return; }
    if (!confirm("Delete category \"" + key + "\"?")) return;
    onSet(cats.filter((c) => c.key !== key), key);
  };
  return (
    <div>
      <div style={{ display: "flex", gap: 10, alignItems: "center", marginBottom: 12 }}>
        <h3 className="gold-text" style={{ fontSize: 20 }}>Categories</h3>
        <button className="btn btn-sm btn-gold" onClick={startNew} style={{ marginLeft: "auto" }}>+ New category</button>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(260px,1fr))", gap: 12 }}>
        {cats.map((c) => {
          const count = games.filter((g) => g.cat === c.key).length;
          return (
            <div key={c.key} style={{ background: "rgba(20,15,30,.8)", border: "1px solid rgba(255,255,255,.08)", borderRadius: 10, padding: 14 }}>
              <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                <span style={{ width: 22, height: 22, borderRadius: 6, background: "linear-gradient(135deg," + c.c[0] + "," + c.c[1] + ")" }} />
                <b style={{ flex: 1 }}>{c.name}</b>
              </div>
              <div className="muted" style={{ fontSize: 12, marginTop: 4 }}>key: {c.key} · {count} game(s)</div>
              <p className="muted" style={{ fontSize: 12, marginTop: 6, marginBottom: 8 }}>{c.blurb}</p>
              <div style={{ display: "flex", gap: 6 }}>
                <button className="btn btn-sm btn-purple" onClick={() => setEditing({ ...c, __origKey: c.key })}>Edit</button>
                <button className="btn btn-sm" style={{ background: "#5a1a1a", color: "#fff" }} onClick={() => remove(c.key)}>Delete</button>
              </div>
            </div>
          );
        })}
      </div>
      {editing && (
        <div style={{ background: "rgba(20,15,30,.9)", border: "1px solid rgba(231,167,43,.25)", borderRadius: 14, padding: 20, marginTop: 16 }}>
          <h4 className="gold-text" style={{ fontSize: 18, marginBottom: 12 }}>{isNew ? "New category" : "Edit category"}</h4>
          <div style={{ display: "grid", gap: 10 }}>
            <label className="muted" style={{ fontSize: 13 }}>Name<input style={{ width: "100%", padding: 10, marginTop: 4, borderRadius: 8, border: "1px solid rgba(255,255,255,.12)", background: "rgba(0,0,0,.3)", color: "#fff" }} value={editing.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /></label>
            <label className="muted" style={{ fontSize: 13 }}>Key (URL slug)<input style={{ width: "100%", padding: 10, marginTop: 4, borderRadius: 8, border: "1px solid rgba(255,255,255,.12)", background: "rgba(0,0,0,.3)", color: "#fff" }} value={editing.key} onChange={(e) => setEditing({ ...editing, key: e.target.value })} /></label>
            <label className="muted" style={{ fontSize: 13 }}>Short label<input style={{ width: "100%", padding: 10, marginTop: 4, borderRadius: 8, border: "1px solid rgba(255,255,255,.12)", background: "rgba(0,0,0,.3)", color: "#fff" }} value={editing.short || ""} onChange={(e) => setEditing({ ...editing, short: e.target.value })} /></label>
            <label className="muted" style={{ fontSize: 13 }}>Blurb<textarea style={{ width: "100%", padding: 10, marginTop: 4, borderRadius: 8, border: "1px solid rgba(255,255,255,.12)", background: "rgba(0,0,0,.3)", color: "#fff", minHeight: 70 }} value={editing.blurb} onChange={(e) => setEditing({ ...editing, blurb: e.target.value })} /></label>
            <div style={{ display: "flex", gap: 12 }}>
              <label className="muted" style={{ fontSize: 13, flex: 1 }}>Colour 1<input type="color" style={{ width: "100%", height: 40, marginTop: 4, padding: 4, borderRadius: 8, border: "1px solid rgba(255,255,255,.12)", background: "rgba(0,0,0,.3)" }} value={editing.c[0]} onChange={(e) => setEditing({ ...editing, c: [e.target.value, editing.c[1]] })} /></label>
              <label className="muted" style={{ fontSize: 13, flex: 1 }}>Colour 2<input type="color" style={{ width: "100%", height: 40, marginTop: 4, padding: 4, borderRadius: 8, border: "1px solid rgba(255,255,255,.12)", background: "rgba(0,0,0,.3)" }} value={editing.c[1]} onChange={(e) => setEditing({ ...editing, c: [editing.c[0], e.target.value] })} /></label>
            </div>
            <div style={{ display: "flex", gap: 10, marginTop: 6 }}>
              <button className="btn btn-gold" onClick={save}>Save</button>
              <button className="btn btn-purple" onClick={() => setEditing(null)}>Cancel</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

/* =================== MAIN ADMIN =================== */
export default function Admin() {
  const { user, isAdmin } = useAuth();
  const [localAuthed, setLocalAuthed] = useState(() => sessionStorage.getItem(SS_AUTH) === "1");
  const [authOpen, setAuthOpen] = useState(false);

  const liveMode = supabaseEnabled && user && isAdmin;
  const authed = liveMode || localAuthed;

  const [tab, setTab] = useState("games");
  const [games, setGames] = useState([]);
  const [cats, setCats]   = useState([]);
  const [editing, setEditing] = useState(null);
  const [q, setQ] = useState("");
  const [filterCat, setFilterCat] = useState("");
  const [toast, setToast] = useState("");
  const [syncing, setSyncing] = useState(false);

  const showToast = (msg) => { setToast(msg); setTimeout(() => setToast(""), 2600); };

  /* load data when authed; prefer live DB if available */
  useEffect(() => {
    if (!authed) return;
    (async () => {
      if (liveMode) {
        setSyncing(true);
        const liveG = await fetchLiveGames();
        const liveC = await fetchLiveCategories();
        setGames(liveG && liveG.length ? liveG : loadLocalGames());
        setCats(liveC && liveC.length ? liveC : loadLocalCats());
        setSyncing(false);
      } else {
        setGames(loadLocalGames());
        setCats(loadLocalCats());
      }
    })();
  }, [authed, liveMode]);

  /* helpers: persist to local + (if liveMode) DB */
  const pushGames = async (next) => {
    saveLocalGames(next); setGames(next);
    if (liveMode) {
      try { await upsertGames(next); showToast("Saved live ✓"); }
      catch (e) { showToast("DB error: " + e.message); }
    } else { showToast("Saved locally."); }
  };
  const pushCats = async (next, removedKey) => {
    saveLocalCats(next); setCats(next);
    if (liveMode) {
      try {
        await upsertCategories(next);
        if (removedKey) await deleteCategoryByKey(removedKey);
        showToast("Saved live ✓");
      } catch (e) { showToast("DB error: " + e.message); }
    } else { showToast("Saved locally."); }
  };

  const onSaveGame = async (g) => {
    let next;
    if (games.find((x) => x.id === g.id)) next = games.map((x) => (x.id === g.id ? g : x));
    else next = [...games, g];
    await pushGames(next);
    setEditing(null);
  };
  const onDeleteGame = async (id) => {
    const next = games.filter((g) => g.id !== id);
    saveLocalGames(next); setGames(next);
    setEditing(null);
    if (liveMode) {
      try { await deleteGameById(id); showToast("Deleted live ✓"); }
      catch (e) { showToast("DB error: " + e.message); }
    } else showToast("Deleted locally.");
  };
  const move = async (id, dir) => {
    const i = games.findIndex((g) => g.id === id);
    const j = i + dir;
    if (i < 0 || j < 0 || j >= games.length) return;
    const next = games.slice(); [next[i], next[j]] = [next[j], next[i]];
    await pushGames(next);
  };

  const filtered = useMemo(() => {
    const s = q.trim().toLowerCase();
    return games.filter((g) => {
      if (filterCat && g.cat !== filterCat) return false;
      if (!s) return true;
      return g.title.toLowerCase().includes(s) || g.slug.toLowerCase().includes(s) || g.dev.toLowerCase().includes(s) || (g.tags || []).join(" ").toLowerCase().includes(s);
    });
  }, [games, q, filterCat]);

  const exportGames = () => downloadText("games.js", exportGamesJs(games));
  const exportCats  = () => downloadText("categories.js", exportCatsJs(cats));
  const resetAll = () => {
    if (!confirm("Reset to the original baked-in data? Clears your local edits.")) return;
    localStorage.removeItem(LS_GAMES); localStorage.removeItem(LS_CATS);
    setGames(JSON.parse(JSON.stringify(BASE_GAMES)));
    setCats(JSON.parse(JSON.stringify(BASE_CATEGORIES)));
    showToast("Reset to defaults.");
  };
  const localLogout = () => { sessionStorage.removeItem(SS_AUTH); setLocalAuthed(false); };

  if (!authed) {
    return (
      <>
        <LoginGate onAuth={() => setLocalAuthed(true)} openSupabaseAuth={() => setAuthOpen(true)} />
        <AuthModal open={authOpen} onClose={() => setAuthOpen(false)} />
      </>
    );
  }

  /* Signed in via Supabase but not an admin */
  if (supabaseEnabled && user && !isAdmin && !localAuthed) {
    return (
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", padding: 20 }}>
        <div style={{ background: "rgba(28,22,40,.85)", border: "1px solid rgba(231,167,43,.3)", borderRadius: 14, padding: 28, maxWidth: 460, textAlign: "center" }}>
          <h2 className="gold-text" style={{ fontSize: 22, marginBottom: 8 }}>Not an admin</h2>
          <p className="muted" style={{ fontSize: 14, marginBottom: 16 }}>
            Your account ({user.email}) isn't flagged as a GameZy admin. Add your UID to the <code>admins</code> table in Supabase (see SETUP-SUPABASE.md step 3) or use the local password.
          </p>
          <code style={{ display: "block", padding: 10, background: "rgba(0,0,0,.4)", borderRadius: 6, fontSize: 12, marginBottom: 16, wordBreak: "break-all" }}>{user.id}</code>
          <Link to="/" className="btn btn-purple btn-sm">Back to site</Link>
        </div>
      </div>
    );
  }

  const btnRow = { display: "flex", gap: 8, flexWrap: "wrap" };

  return (
    <div style={{ paddingTop: 110, paddingBottom: 80 }}>
      <div className="wrap">
        <div style={{ display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap", marginBottom: 16 }}>
          <h1 className="gold-text" style={{ fontSize: 30, fontWeight: 800 }}>Admin</h1>
          <span className="muted" style={{ fontSize: 14 }}>
            {liveMode ? "Live mode — changes go to everyone" : "Local mode — changes stay in your browser"}
            {" · "}{games.length} games · {cats.length} categories{syncing ? " · syncing…" : ""}
          </span>
          <div style={{ marginLeft: "auto", ...btnRow }}>
            <button className="btn btn-sm btn-purple" onClick={exportGames}>Export games.js</button>
            <button className="btn btn-sm btn-purple" onClick={exportCats}>Export categories.js</button>
            <button className="btn btn-sm" style={{ background: "#5a1a1a", color: "#fff" }} onClick={resetAll}>Reset local</button>
            {localAuthed && !liveMode && <button className="btn btn-sm" style={{ background: "rgba(255,255,255,.08)", color: "#fff" }} onClick={localLogout}>Sign out</button>}
          </div>
        </div>

        <div style={{ display: "flex", gap: 6, marginBottom: 18, borderBottom: "1px solid rgba(255,255,255,.08)" }}>
          {["games", "categories", "help"].map((t) => (
            <button key={t} onClick={() => setTab(t)}
              style={{ padding: "10px 16px", background: "transparent", color: tab === t ? "#f6c558" : "#cbb8e4", border: "none", borderBottom: tab === t ? "2px solid #f6c558" : "2px solid transparent", fontSize: 15, cursor: "pointer", textTransform: "capitalize" }}>{t}</button>
          ))}
        </div>

        {tab === "games" && (
          <>
            <div style={{ display: "flex", gap: 10, marginBottom: 14, flexWrap: "wrap" }}>
              <input placeholder="Search games…" value={q} onChange={(e) => setQ(e.target.value)} style={{ flex: "1 1 240px", padding: "10px 12px", borderRadius: 8, border: "1px solid rgba(255,255,255,.12)", background: "rgba(0,0,0,.3)", color: "#fff" }} />
              <select value={filterCat} onChange={(e) => setFilterCat(e.target.value)} style={{ padding: "10px 12px", borderRadius: 8, border: "1px solid rgba(255,255,255,.12)", background: "rgba(0,0,0,.3)", color: "#fff" }}>
                <option value="">All categories</option>
                {cats.map((c) => <option key={c.key} value={c.key}>{c.name}</option>)}
              </select>
              <button className="btn btn-gold" onClick={() => setEditing(emptyGame())}>+ Add game</button>
            </div>

            <div style={{ background: "rgba(20,15,30,.6)", borderRadius: 10, overflow: "hidden", border: "1px solid rgba(255,255,255,.06)" }}>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 110px 130px 90px 200px", padding: "10px 14px", background: "rgba(0,0,0,.3)", fontSize: 12, color: "#cbb8e4", textTransform: "uppercase", letterSpacing: 0.5 }}>
                <div>Title</div><div>Category</div><div>Platforms</div><div>Rating</div><div style={{ textAlign: "right" }}>Actions</div>
              </div>
              {filtered.length === 0 && <div style={{ padding: 20, textAlign: "center" }} className="muted">No games match.</div>}
              {filtered.map((g) => {
                const cat = cats.find((c) => c.key === g.cat);
                return (
                  <div key={g.id} style={{ display: "grid", gridTemplateColumns: "1fr 110px 130px 90px 200px", padding: "12px 14px", borderTop: "1px solid rgba(255,255,255,.05)", alignItems: "center", fontSize: 14 }}>
                    <div><b>{g.title}</b><div className="muted" style={{ fontSize: 12 }}>{g.slug} · {g.dev} · {g.year}</div></div>
                    <div className="muted" style={{ fontSize: 13 }}>{cat ? cat.name : g.cat}</div>
                    <div className="muted" style={{ fontSize: 12 }}>{(g.plat || []).join(", ")}</div>
                    <div>★ {parseFloat(g.rating).toFixed(1)}</div>
                    <div style={{ display: "flex", gap: 6, justifyContent: "flex-end" }}>
                      <button className="btn btn-sm" style={{ background: "rgba(255,255,255,.08)", color: "#fff", padding: "4px 8px" }} onClick={() => move(g.id, -1)}>↑</button>
                      <button className="btn btn-sm" style={{ background: "rgba(255,255,255,.08)", color: "#fff", padding: "4px 8px" }} onClick={() => move(g.id, 1)}>↓</button>
                      <button className="btn btn-sm btn-purple" onClick={() => setEditing(g)}>Edit</button>
                    </div>
                  </div>
                );
              })}
            </div>

            {editing && <GameEditor key={editing.id} game={editing} cats={cats} onSave={onSaveGame} onCancel={() => setEditing(null)} onDelete={onDeleteGame} />}
          </>
        )}

        {tab === "categories" && (
          <CategoryEditor cats={cats} onSet={pushCats} games={games} />
        )}

        {tab === "help" && (
          <div style={{ background: "rgba(20,15,30,.7)", border: "1px solid rgba(255,255,255,.08)", borderRadius: 12, padding: 22, lineHeight: 1.7 }}>
            <h3 className="gold-text" style={{ fontSize: 20, marginBottom: 10 }}>How edits go live</h3>
            <p className="muted" style={{ fontSize: 14 }}>
              {liveMode ? (
                <>You're signed in as an <b>admin</b> with Supabase connected. Every save you make here pushes to the database and is visible to every visitor on gamez-y.com instantly.</>
              ) : (
                <>You're in <b>local mode</b>. Edits only affect your browser. To make changes visible to everyone, either sign in with an admin GameZy account (recommended), or click <b>Export</b> and replace the matching file in <code>src/data/</code>, then <code>git push</code>.</>
              )}
            </p>
            <h3 className="gold-text" style={{ fontSize: 20, marginTop: 22, marginBottom: 10 }}>Game images</h3>
            <p className="muted" style={{ fontSize: 14 }}>Drop a poster into <code>public/images/games/&lt;slug&gt;.jpg</code> (matching the game's slug). Or paste an explicit URL into the "Image path" field on a game.</p>
            <h3 className="gold-text" style={{ fontSize: 20, marginTop: 22, marginBottom: 10 }}>Local password</h3>
            <p className="muted" style={{ fontSize: 14 }}>Edit <code>src/pages/Admin.jsx</code> line <code>const ADMIN_PASSWORD = "&hellip;"</code>.</p>
          </div>
        )}

        {toast && (
          <div style={{ position: "fixed", bottom: 30, right: 30, background: "rgba(231,167,43,.95)", color: "#1a0e2e", padding: "12px 18px", borderRadius: 10, fontWeight: 600, boxShadow: "0 10px 30px rgba(0,0,0,.4)", zIndex: 9999 }}>{toast}</div>
        )}
      </div>
    </div>
  );
}
